version: '3.7'

services:
  app_builder:
    container_name: java_app_builder
    build:
      context: ./..
      dockerfile: ./docker/app_builder/Dockerfile
    volumes:
      - ../:/app
    entrypoint: mvn install
